### ISSUE TITLE
Welcoming Suggestion

### ISSUE THREAD

**Issue by PCAwesomeness** [Guild-Hall/MHFC#1]
Hello! I'm so glad to see that you set up a GitHub! ^_^

Now, to the main point. When will you add Danieru's Tigrex and Deviljho to this?

EDIT: Oh wait, this is not going to be updated anymore. Sorry for leaving this suggestion here.

**Comment by PCAwesomeness** [comment]
When will the new Rathalos and Deviljho be added to this, along with all the mobs from the older builds?

**Comment by WorldSEnder** [comment]
We just finished up reworking a huge part of the mod, so expect Tigrex in 2 weeks, and Deviljho maybe 2 weeks later.

**Comment by PCAwesomeness** [comment]
What about the Rathalos?

**Comment by WorldSEnder** [comment]
Rathalos will most likely come with Deviljho. First and foremost we will finish Tigrex

**Comment by PCAwesomeness** [comment]
OK!

**Comment by WorldSEnder** [comment]
Tigrex is in the beta release, feel free to test it out
