### ISSUE TITLE
Gamerule and mod

### ISSUE THREAD

**Issue by kurotom** [Guild-Hall/MHFC#28]
Hello, I added the mod to the game all right until I entered to play the world, the problem is that there are no "mobs" and apparently this is deactivated when starting with this mod, change the rule "/gamerule doMobSpawning true" to "/gamerule doMobSpawning false ".

Each time when closing and opening the server it changes to false, and it has to be changed manually. It is extremely uncomfortable.

I don't know if it's because the mod is like that or it's just a mistake. I was looking in the configuration files and did not find any option to change this situation.
I don't think it's a critical error, but I considered it correct to report this.

I find your mod interesting, regards.

**Comment by WorldSEnder** [comment]
We are meddling with `doMobSpawning`, although that was only meant to effect our custom dimension. Uncontrolled mob spawns there would be annoying during a quest. So it might have an unwanted effect on the overworld. What versions of minecraft/mod are you running @kurotom ?

**Comment by kurotom** [comment]
Minecraft version:    -1.12.2
Forge version:    -1.12.2-forge1.12.2-14.23.5.2838

Mod version:  -mhfc-1.4.8.1500-1.12.2+1.12.2.jar
                       -mcanm-2.7.4.149-a7cc834+1.12.2.jar
                       -worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar

**Comment by WorldSEnder** [comment]
Just pushed 7fc754ee4c9d3bcb770772e1ed708900a718f447 which instead of relying on game rules, prevents entity spawning via event listener
