### ISSUE TITLE
A world to raid in, a world to die in.

### ISSUE THREAD

**Issue by WorldSEnder** [Guild-Hall/MHFC#3]
We want to make a custom world where our quests take place. This is so that you can fight boss monsters in restricted terrain and not run away *evil laughter* like you can when slaying beasts in the vanilla world.
You will take quests from the Guild which teleport you into this world where you can find unique structures and areas aswell as materials.

**Comment by WorldSEnder** [comment]
The dimension now exist. Actual areas to fight are still WIP

**Comment by HeroicKatora** [comment]
Areas can now be requested and are then created in a non-disruptive way.
You can inspect one by teleporting via a command or by accepting a quest.
An world open for exploration is coming soon.
