### ISSUE TITLE
Tigrex

### ISSUE THREAD

**Issue by PCAwesomeness** [Guild-Hall/MHFC#5]
Will you make it so Tigrex is able to step up 1 block and/or break walls higher than 1 block while charging? Fighting him on a regular world gets him stuck all the time.

**Comment by Heltrato** [comment]
Hmm yeah we gonna work on that.. Anyways did u get all the sounds for tigrex?

**Comment by WorldSEnder** [comment]
At least the animations are now fixed, stepping coming up soon

**Comment by HeroicKatora** [comment]
This feature is now enable. Making it more visually appealing on the client side is next on the list since he appears stuck a little bit in the ground atm.
