### ISSUE TITLE
Deviljho

### ISSUE THREAD

**Issue by PCAwesomeness** [Guild-Hall/MHFC#7]
So far, the big Brute Wyvern is working well, but I have a few issues to report:

1: You made it so Deviljho was able to step up 1 block when pursuing you, right? If you did or did not, there's still a problem. Running away from him on a regular world sometimes gets him stuck.

2: When you're 5 blocks away from him, he roars copiously. May you please fix this and make it so he starts biting you and/or hitting you with his tail after roaring once or twice, and only roaring slightly less often than Tigrex?

3: I fixed up a new roar sound for Deviljho (it's in the most recent file that I sent to Heltrato), so, you might want to use that.

4: You might want to adjust the bite noise so it starts at the beginning of the animation. If you don't want to, it's OK; I can just fix up 2 new bite noises and send them to you.

**Comment by Heltrato** [comment]
Looks like WorldSEnder is here, 

1.) Could you send a screenshot in the sky group

2.) Seems a glitch going to take a look at.

3.) Okay going too look

4.)You Might fix the sound it really doesnt work well

**Comment by PCAwesomeness** [comment]
OK!

**Comment by PCAwesomeness** [comment]
Will be transferred onto a new issue.

**Comment by WorldSEnder** [comment]
See #13
