### ISSUE TITLE
Comprehensible user interface

### ISSUE THREAD

**Issue by HeroicKatora** [Guild-Hall/MHFC#9]
Feedback has determined that the current ui used for displaying active quests needs to be overhauled. It causes issues when buffs are active and when active with any other kind of modification of the inventory gui.

**Comment by Heltrato** [comment]
going to try check if this still persist in my next build.

**Comment by HeroicKatora** [comment]
Fixed this by adding a new screen instead of forcing everything onto the main inventory screen. This should also give us more options of how to display the quest screen exactly, like adding tabs etc.
